[project]
name = "landy_ai"
version = "0.1.0"
dependencies = [
    "fastapi",
    "pydantic",
    "langgraph",
    "typing-extensions",
    "langchain-openai",
    "python-dotenv",
]

[project.scripts]
app = "src.index:app"

[tool.vercel.scripts]
build = "python build.py"
